import React from 'react';
import {
  Home,
  AppWindow,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  NavArrowRight,
  NavArrowLeft,
  NavArrowUp,
  NavArrowDown,
  LogOut,
  Menu,
  MoreVert,
  MoreHoriz,
  Search,
  Plus,
  PlusCircle,
  Minus,
  MinusCircle,
  Xmark,
  XmarkCircle,
  Check,
  CheckCircle,
  EditPencil,
  Trash,
  Bin,
  Copy,
  Download,
  Upload,
  Refresh,
  Filter,
  FilterAlt,
  Eye,
  EyeClosed,
  Lock,
  ShareAndroid,
  Link,
  Mail,
  ChatBubble,
  Bell,
  Microphone,
  Play,
  Pause,
  Camera,
  MusicDoubleNote,
  List,
  MultiplePages,
  Box,
  ViewGrid,
  ViewColumns2,
  GraphUp,
  GraphDown,
  Suitcase,
  Building,
  CreditCard,
  Cart,
  Rocket,
  Bug,
  Database,
  Cloud,
  Laptop,
  Wifi,
  User,
  Group,
  Calendar,
  Clock,
  Folder,
  Page,
  Star,
  Heart,
  MapPin,
  Settings,
  InfoCircle,
  WarningTriangle,
  HelpCircle,
  Brain,
  Flash,
  UserCircle,
  PasteClipboard,
  Code,
  Cpu,
  Rhombus,
  LogIn,
  Facebook,
  WhiteFlag,
  TriangleFlag,
  FireFlame,
  Globe,
  Google,
  GraduationCap,
  Headset,
  MediaImage,
  Archive,
  Linkedin,
  NumberedListLeft,
  MagicWand,
  Megaphone,
  MoonSat,
  Palette,
  Presentation,
  Quote,
  Redo,
  ShieldCheck,
  Spotify,
  Label,
  PrecisionTool,
  Terminal,
  ThumbsUp,
  ThumbsDown,
  VideoCamera,
  Whatsapp,
  Twitter,
  FloppyDisk,
  Key,
  Network,
  Book,
  BookStack,
  SystemRestart,
  FrameTool,
  StatsReport,
  DatabaseCheck,
  CloudUpload,
  DiceFive,
  EmojiTalkingHappy,
  LightBulb,
  Medal,
  OpenBook,
  Trophy,
  PathArrow,
  Crown,
  Movie,
  PenTablet,
  UserPlus,
  Coins,
  StatDown,
  StatUp,
  Shield,
  Reports,
  Erase,
  SoundHigh,
  Send,
  ControlSlider,
  MoreVertCircle,
  MoreHorizCircle,
  Expand,
  Compress,
  Sort,
  SunLight,
  Fingerprint,
  Cube,
  WindowTabs,
  Table,
  ZoomIn,
  ZoomOut,
  SidebarCollapse,
  CursorPointer,
  Dollar,
  Gift,
  UserBadgeCheck,
  SmartphoneDevice,
  DesignNib,
  Bold,
  Italic,
  Strikethrough,
  Undo,
  Cookie,
  CloudXmark,
  Bookmark,
  BookmarkSolid,
  UserXmark,
  TimerOff,
  Timer,
  Magnet,
  MultiWindow,
  Component,
  Underline,
  AppleMac,
  SineWave,
  Circle,
  ReportColumns,
  BellNotification,
  TriangleFlagCircle,
  PeaceHand,
  EmptyPage,
  Infinite,
  Server,
  AppWindow as WindowIcon,
  QuestionMark,
  Wrench,
} from 'iconoir-react';

// All valid icon names - TypeScript will catch invalid icons at build time
export const iconMap = {
  // Navegação
  home: Home,
  apps: AppWindow,
  'arrow-right': ArrowRight,
  'arrow-left': ArrowLeft,
  'arrow-small-up': ArrowUp,
  'arrow-small-down': ArrowDown,
  'angle-small-right': NavArrowRight,
  'angle-small-left': NavArrowLeft,
  'angle-small-up': NavArrowUp,
  'angle-small-down': NavArrowDown,
  'angle-double-right': NavArrowRight,
  'angle-double-left': NavArrowLeft,
  'chevron-right': NavArrowRight,
  'chevron-down': NavArrowDown,
  'chevron-up': NavArrowUp,
  'chevron-left': NavArrowLeft,
  'sign-out-alt': LogOut,
  'menu-burger': Menu,
  'menu-dots': MoreVert,
  'menu-dots-h': MoreHoriz,
  'menu-dots-vertical': MoreVertCircle,
  enter: LogIn,
  exit: LogOut,
  expand: Expand,
  compress: Compress,

  // Ações
  search: Search,
  'search-alt': Search,
  plus: Plus,
  'plus-circle': PlusCircle,
  minus: Minus,
  'minus-circle': MinusCircle,
  cross: Xmark,
  'cross-circle': XmarkCircle,
  times: Xmark,
  check: Check,
  'check-circle': CheckCircle,
  pencil: EditPencil,
  edit: EditPencil,
  'file-edit': Page,
  trash: Bin,
  copy: Copy,
  duplicate: Copy,
  download: Download,
  upload: Upload,
  refresh: Refresh,
  filter: Filter,
  'filter-alt': FilterAlt,
  eye: Eye,
  'eye-crossed': EyeClosed,
  lock: Lock,
  unlock: Key,
  share: ShareAndroid,
  link: Link,
  save: FloppyDisk,
  redo: Redo,
  undo: Redo,
  eraser: Erase,

  // Comunicação
  envelope: Mail,
  'comment-alt': ChatBubble,
  bell: Bell,
  megaphone: Megaphone,
  microphone: Microphone,
  play: Play,
  pause: Pause,
  camera: Camera,
  'video-camera': VideoCamera,
  music: MusicDoubleNote,
  headset: Headset,
  'paper-plane': Send,
  picture: MediaImage,
  volume: SoundHigh,

  // Interface
  list: List,
  'list-ul': List,
  'list-ol': NumberedListLeft,
  layers: MultiplePages,
  box: Box,
  grid: ViewGrid,
  'layout-fluid': ViewGrid,
  columns: ViewColumns2,
  clip: PasteClipboard,
  clipboard: PasteClipboard,
  'clipboard-list': PasteClipboard,
  'settings-sliders': ControlSlider,
  'sort-alt': Sort,
  fingerprint: Fingerprint,
  cube: Cube,
  browser: AppWindow,
  table: Table,
  'zoom-in': ZoomIn,
  'zoom-out': ZoomOut,
  sidebar: SidebarCollapse,
  cursor: CursorPointer,
  'cursor-finger': CursorPointer,

  // Negócios
  'chart-histogram': GraphUp,
  'chart-line': StatUp,
  'chart-line-down': StatDown,
  'chart-pie': Reports,
  briefcase: Suitcase,
  building: Building,
  'credit-card': CreditCard,
  'shopping-cart': Cart,
  rocket: Rocket,
  coins: Coins,
  dollar: Dollar,
  receipt: Reports,
  target: PrecisionTool,
  presentation: Presentation,
  stats: StatsReport,

  // Tech
  bug: Bug,
  database: Database,
  cloud: Cloud,
  laptop: Laptop,
  wifi: Wifi,
  cpu: Cpu,
  'microchip-ai': Cpu,
  code: Code,
  'code-simple': Code,
  terminal: Terminal,
  sitemap: Network,
  'chart-network': Network,
  disk: FloppyDisk,
  mobile: SmartphoneDevice,
  network: Network,

  // Usuários
  user: User,
  users: Group,
  'users-alt': Group,
  'user-add': UserPlus,
  'user-time': Clock,
  'id-badge': UserBadgeCheck,
  'address-book': Book,
  portrait: UserCircle,
  following: Group,
  'circle-user': UserCircle,

  // Geral
  calendar: Calendar,
  clock: Clock,
  sun: SunLight,
  moon: MoonSat,
  folder: Folder,
  document: Page,
  star: Star,
  heart: Heart,
  'map-marker': MapPin,
  road: PathArrow,
  route: PathArrow,
  settings: Settings,
  info: InfoCircle,
  exclamation: WarningTriangle,
  'exclamation-triangle': WarningTriangle,
  interrogation: HelpCircle,
  'circle-question': HelpCircle,
  brain: Brain,
  'brain-circuit': Brain,
  zap: Flash,
  bolt: Flash,
  bulb: LightBulb,
  lightbulb: LightBulb,
  award: Medal,
  medal: Medal,
  library: BookStack,
  book: Book,
  'book-stack': BookStack,
  'book-open-cover': OpenBook,
  'book-alt': OpenBook,
  image: MediaImage,
  inbox: Archive,
  tag: Label,
  tags: Label,
  'thumbs-up': ThumbsUp,
  'thumbs-down': ThumbsDown,
  'graduation-cap': GraduationCap,
  'shield-check': ShieldCheck,
  shield: Shield,
  palette: Palette,
  'magic-wand': MagicWand,
  diamond: Rhombus,
  key: Key,
  trophy: Trophy,
  crown: Crown,
  'photo-video': Movie,
  'pen-nib': DesignNib,
  robot: EmojiTalkingHappy,
  gift: Gift,

  // Re-mappings (aliases for compatibility)
  'check-double': Check,
  'check-square': Check,
  'file-code': Code,
  'file-plus': Page,
  'folder-open': Folder,
  'folder-tree': Folder,
  globe: Globe,
  layout: ViewGrid,
  'quote-left': Quote,
  'quote-right': Quote,
  video: VideoCamera,

  // Social media
  whatsapp: Whatsapp,
  facebook: Facebook,
  linkedin: Linkedin,
  twitter: Twitter,
  spotify: Spotify,
  google: Google,

  // Groups Dashboard icons
  'graph-up': GraphUp,
  'graph-down': GraphDown,
  'stats-report': StatsReport,
  activity: GraphUp,
  'pin-alt': MapPin,
  'chat-bubble': ChatBubble,
  'layout-grid': ViewGrid,
  'refresh-double': SystemRestart,
  page: Page,
  group: Group,

  // LMS icons
  'angle-left': NavArrowLeft,
  'angle-right': NavArrowRight,
  'badge-check': UserBadgeCheck,
  'file-pdf': Page,
  'file-text': Page,
  'file-csv': Page,
  'file-check': Page,
  'folder-zip': Folder,
  'play-circle': Play,
  'trend-up': StatUp,
  'external-link': ShareAndroid,
  discord: ChatBubble,
  'flower-tulip': Heart,
  gym: User,

  // Text formatting icons
  bold: Bold,
  italic: Italic,
  strikethrough: Strikethrough,
  'rotate-left': Undo,
  'rotate-right': Redo,

  // Additional icons
  flame: FireFlame,
  'fire-flame': FireFlame,
  cookie: Cookie,
  'cloud-slash': CloudXmark,
  'cloud-xmark': CloudXmark,
  spinner: Refresh,
  sparkles: MagicWand,
  'id-card-clip-alt': UserBadgeCheck,

  // Missing aliases (icon audit fix)
  'angle-down': NavArrowDown,
  'angle-up': NavArrowUp,
  'arrow-down': ArrowDown,
  'arrow-up': ArrowUp,
  bookmark: Bookmark,
  'box-open': Box,
  'cloud-upload': CloudUpload,
  'comment-alt-middle': ChatBubble,
  'comment-quote': Quote,
  'dollar-sign': Dollar,
  'exclamation-circle': WarningTriangle,
  flash: Flash,
  'info-circle': InfoCircle,
  label: Label,
  'laptop-code': Laptop,
  'lightbulb-on': LightBulb,
  lightning: Flash,
  'list-check': Check,
  loader: Refresh,
  microchip: Cpu,
  'network-cloud': Network,
  'project-diagram': Network,
  pulse: SineWave,
  quote: Quote,
  'time-fast': Timer,
  'time-past': TimerOff,
  university: GraduationCap,
  'user-delete': UserXmark,
  'warning-triangle': WarningTriangle,
  'x-circle': XmarkCircle,
  xmark: Xmark,
  plug: Link,
  magnet: Magnet,
  'multi-window': MultiWindow,
  component: Component,
  underline: Underline,
  apple: AppleMac,
  archive: Archive,
  flag: TriangleFlag,
  circle: Circle,
  microsoft: Building,
  amazon: Cart,

  // Config icon aliases (icon: 'name' pattern)
  'alert-circle': BellNotification,
  ban: XmarkCircle,
  'bar-chart': GraphUp,
  'book-open': OpenBook,
  bullseye: PrecisionTool,
  'chat-alt': ChatBubble,
  'code-branch': Network,
  cog: Settings,
  compass: Globe,
  'document-text': Page,
  file: Page,
  gem: Rhombus,
  'git-branch': Network,
  'grid-3x3': ViewGrid,
  heartbeat: Heart,
  'layer-group': MultiplePages,
  'layout-dashboard': ViewGrid,
  'play-alt': Play,
  power: Flash,
  puzzle: Cube,
  question: QuestionMark,
  scale: Rhombus,
  send: Send,
  server: Server,
  'shield-exclamation': Shield,
  tools: Wrench,
  triangle: TriangleFlagCircle,
  type: Bold,
  warning: WarningTriangle,
  window: WindowIcon,
  infinity: Infinite,
  bridge: Link,
  'hourglass-end': Clock,
  text: Page,
  'user-circle': UserCircle,
} as const satisfies Record<string, React.ComponentType<any>>;

// Type for all valid icon names - TypeScript will catch invalid icons at build time
export type IconName = keyof typeof iconMap;

// List of all valid icon names (for runtime validation and documentation)
export const validIconNames = Object.keys(iconMap) as IconName[];

// Fallback for missing icons
export const DefaultIcon = HelpCircle;

// Helper to check if icon exists (runtime validation)
export const hasIcon = (name: string): name is IconName =>
  Object.prototype.hasOwnProperty.call(iconMap, name);
