import {
    Home,
    AppWindow,
    ArrowRight,
    ArrowLeft,
    ArrowUp,
    ArrowDown,
    NavArrowRight,
    NavArrowLeft,
    NavArrowUp,
    NavArrowDown,
    LogOut,
    Menu,
    MoreVert,
    MoreHoriz,
    Search,
    Plus,
    PlusCircle,
    Minus,
    MinusCircle,
    Xmark,
    XmarkCircle,
    Check,
    CheckCircle,
    EditPencil,
    Trash,
    Bin,
    Copy,
    Download,
    Upload,
    Refresh,
    Filter,
    FilterAlt,
    Eye,
    EyeClosed,
    Lock,
    ShareAndroid,
    Link,
    Mail,
    ChatBubble,
    Bell,
    Microphone,
    Play,
    Pause,
    Camera,
    MusicDoubleNote,
    List,
    MultiplePages,
    Box,
    ViewGrid,
    ViewColumns2,
    GraphUp,
    GraphDown,
    Suitcase,
    Building,
    CreditCard,
    Cart,
    Rocket,
    Bug,
    Database,
    Cloud,
    Laptop,
    Wifi,
    User,
    Group,
    Calendar,
    Clock,
    Folder,
    Page,
    Star,
    Heart,
    MapPin,
    Settings,
    InfoCircle,
    WarningTriangle,
    HelpCircle,
    Brain,
    Flash,
    UserCircle,
    PasteClipboard,
    Code,
    Cpu,
    Rhombus,
    LogIn,
    Facebook,
    WhiteFlag,
    TriangleFlag,
    FireFlame,
    Globe,
    Google,
    GraduationCap,
    Headset,
    MediaImage,
    Archive,
    Linkedin,
    NumberedListLeft,
    MagicWand,
    Megaphone,
    MoonSat,
    Palette,
    Presentation,
    Quote,
    Redo,
    ShieldCheck,
    Spotify,
    Label,
    PrecisionTool,
    Terminal,
    ThumbsUp,
    ThumbsDown,
    VideoCamera,
    Whatsapp,
    Twitter,
    FloppyDisk,
    Key,
    Network,
    Book,
    BookStack,
    SystemRestart,
    FrameTool,
    StatsReport,
    DatabaseCheck,
    CloudUpload,
    DiceFive,
    EmojiTalkingHappy,
    LightBulb,
    Medal,
    OpenBook,
    Trophy,
    PathArrow,
    Crown,
    Movie,
    PenTablet,
    UserPlus,
    Coins,
    StatDown,
    StatUp,
    Shield,
    Reports,
    Erase,
    SoundHigh,
    Send,
    ControlSlider,
    MoreVertCircle,
    MoreHorizCircle,
    Expand,
    Compress,
    Sort,
    SunLight,
    Fingerprint,
    Cube,
    WindowTabs,
    Table,
    ZoomIn,
    ZoomOut,
    SidebarCollapse,
    CursorPointer,
    Dollar,
    Gift,
    UserBadgeCheck,
    SmartphoneDevice,
    DesignNib,
} from 'iconoir-react';

export const iconMap: Record<string, any> = {
    // Navegação
    'home': Home,
    'apps': AppWindow,
    'arrow-right': ArrowRight,
    'arrow-left': ArrowLeft,
    'arrow-small-up': ArrowUp,
    'arrow-small-down': ArrowDown,
    'angle-small-right': NavArrowRight,
    'angle-small-left': NavArrowLeft,
    'angle-small-up': NavArrowUp,
    'angle-small-down': NavArrowDown,
    'angle-double-right': NavArrowRight,
    'angle-double-left': NavArrowLeft,
    'chevron-right': NavArrowRight,
    'chevron-down': NavArrowDown,
    'chevron-up': NavArrowUp,
    'chevron-left': NavArrowLeft,
    'sign-out-alt': LogOut,
    'menu-burger': Menu,
    'menu-dots': MoreVert,
    'menu-dots-h': MoreHoriz,
    'menu-dots-vertical': MoreVertCircle,
    'enter': LogIn,
    'exit': LogOut,
    'expand': Expand,
    'compress': Compress,

    // Ações
    'search': Search,
    'search-alt': Search,
    'plus': Plus,
    'plus-circle': PlusCircle,
    'minus': Minus,
    'minus-circle': MinusCircle,
    'cross': Xmark,
    'cross-circle': XmarkCircle,
    'times': Xmark,
    'check': Check,
    'check-circle': CheckCircle,
    'pencil': EditPencil,
    'edit': EditPencil,
    'file-edit': Page,
    'trash': Bin,
    'copy': Copy,
    'duplicate': Copy,
    'download': Download,
    'upload': Upload,
    'refresh': Refresh,
    'filter': Filter,
    'filter-alt': FilterAlt,
    'eye': Eye,
    'eye-crossed': EyeClosed,
    'lock': Lock,
    'unlock': Key,
    'share': ShareAndroid,
    'link': Link,
    'save': FloppyDisk,
    'redo': Redo,
    'undo': Redo,
    'eraser': Erase,

    // Comunicação
    'envelope': Mail,
    'comment-alt': ChatBubble,
    'bell': Bell,
    'megaphone': Megaphone,
    'microphone': Microphone,
    'play': Play,
    'pause': Pause,
    'camera': Camera,
    'video-camera': VideoCamera,
    'music': MusicDoubleNote,
    'headset': Headset,
    'paper-plane': Send,
    'picture': MediaImage,
    'volume': SoundHigh,

    // Interface
    'list': List,
    'list-ul': List,
    'list-ol': NumberedListLeft,
    'layers': MultiplePages,
    'box': Box,
    'grid': ViewGrid,
    'layout-fluid': ViewGrid,
    'columns': ViewColumns2,
    'clip': PasteClipboard,
    'clipboard': PasteClipboard,
    'clipboard-list': PasteClipboard,
    'settings-sliders': ControlSlider,
    'sort-alt': Sort,
    'fingerprint': Fingerprint,
    'cube': Cube,
    'browser': AppWindow,
    'table': Table,
    'zoom-in': ZoomIn,
    'zoom-out': ZoomOut,
    'sidebar': SidebarCollapse,
    'cursor': CursorPointer,
    'cursor-finger': CursorPointer,

    // Negócios
    'chart-histogram': GraphUp,
    'chart-line': StatUp,
    'chart-line-down': StatDown,
    'chart-pie': Reports,
    'briefcase': Suitcase,
    'building': Building,
    'credit-card': CreditCard,
    'shopping-cart': Cart,
    'rocket': Rocket,
    'coins': Coins,
    'dollar': Dollar,
    'receipt': Reports,
    'target': PrecisionTool,
    'presentation': Presentation,
    'stats': StatsReport,

    // Tech
    'bug': Bug,
    'database': Database,
    'cloud': Cloud,
    'laptop': Laptop,
    'wifi': Wifi,
    'cpu': Cpu,
    'microchip-ai': Cpu,
    'code': Code,
    'code-simple': Code,
    'terminal': Terminal,
    'sitemap': Network,
    'chart-network': Network,
    'disk': FloppyDisk,
    'mobile': SmartphoneDevice,
    'network': Network,

    // Usuários
    'user': User,
    'users': Group,
    'users-alt': Group,
    'user-add': UserPlus,
    'user-time': Clock,
    'id-badge': UserBadgeCheck,
    'address-book': Book,
    'portrait': UserCircle,
    'following': Group,
    'circle-user': UserCircle,

    // Geral
    'calendar': Calendar,
    'clock': Clock,
    'sun': SunLight,
    'moon': MoonSat,
    'folder': Folder,
    'document': Page,
    'star': Star,
    'heart': Heart,
    'map-marker': MapPin,
    'road': PathArrow,
    'route': PathArrow,
    'settings': Settings,
    'info': InfoCircle,
    'exclamation': WarningTriangle,
    'exclamation-triangle': WarningTriangle,
    'interrogation': HelpCircle,
    'circle-question': HelpCircle,
    'brain': Brain,
    'brain-circuit': Brain,
    'zap': Flash,
    'bolt': Flash,
    'bulb': LightBulb,
    'lightbulb': LightBulb,
    'award': Medal,
    'medal': Medal,
    'library': BookStack,
    'book': Book,
    'book-stack': BookStack,
    'book-open-cover': OpenBook,
    'book-alt': OpenBook,
    'image': MediaImage,
    'inbox': Archive,
    'tag': Label,
    'tags': Label,
    'thumbs-up': ThumbsUp,
    'thumbs-down': ThumbsDown,
    'graduation-cap': GraduationCap,
    'shield-check': ShieldCheck,
    'shield': Shield,
    'palette': Palette,
    'magic-wand': MagicWand,
    'diamond': Rhombus,
    'key': Key,
    'trophy': Trophy,
    'crown': Crown,
    'photo-video': Movie,
    'pen-nib': DesignNib,
    'robot': EmojiTalkingHappy,
    'gift': Gift,
};

// Re-mappings for extra safety
iconMap['check-double'] = Check;
iconMap['check-square'] = Check;
iconMap['file-code'] = Code;
iconMap['file-plus'] = Page;
iconMap['folder-open'] = Folder;
iconMap['folder-tree'] = Folder;
iconMap['globe'] = Globe;
iconMap['layout'] = ViewGrid;
iconMap['quote-left'] = Quote;
iconMap['quote-right'] = Quote;
iconMap['stats'] = StatsReport;
iconMap['video'] = VideoCamera;

// Social media
iconMap['whatsapp'] = Whatsapp;
iconMap['facebook'] = Facebook;
iconMap['linkedin'] = Linkedin;
iconMap['twitter'] = Twitter;
iconMap['spotify'] = Spotify;
iconMap['google'] = Google;

// Groups Dashboard icons
iconMap['graph-up'] = GraphUp;
iconMap['graph-down'] = GraphDown;
iconMap['stats-report'] = StatsReport;
iconMap['activity'] = GraphUp;
iconMap['pin-alt'] = MapPin;
iconMap['chat-bubble'] = ChatBubble;
iconMap['layout-grid'] = ViewGrid;
iconMap['refresh-double'] = SystemRestart;
iconMap['page'] = Page;
iconMap['group'] = Group;

// Fallback for missing icons
export const DefaultIcon = HelpCircle;

// Helper to check if icon exists
export const hasIcon = (name: string) => !!iconMap[name];
